################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
common/lib_opt/ctrl_opt_adaptivity.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_adaptivity.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_adv_conn.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_adv_conn.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_adv_nconn.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_adv_nconn.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_ae.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_ae.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_ble_health.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_ble_health.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_cm.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_cm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_connectable.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_connectable.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_connection_handover.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_connection_handover.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_cs.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_cs.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_cs_test.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_cs_test.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_dmm.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_dmm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_dmm_dynamic_priority.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_dmm_dynamic_priority.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_ext_vendor_specific_cmd.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_ext_vendor_specific_cmd.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_health_check.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_health_check.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_initiator.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_initiator.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_legacy_cmd.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_legacy_cmd.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_padv.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_padv.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_past_receiver.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_past_receiver.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_past_sender.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_past_sender.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_pawr_scan.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_pawr_scan.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_power_control.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_power_control.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_pscan.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_pscan.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_rssi_monitor.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_rssi_monitor.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_scanner.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_scanner.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_vendor_specific_cmd.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_vendor_specific_cmd.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/host_opt_gap_bond_mgr.o: D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/lib_opt/src/host_opt_gap_bond_mgr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"D:/ti/ccs2041/ccs/tools/compiler/ti-cgt-armllvm_4.0.4.LTS/bin/tiarmclang.exe" -c @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/build_components.opt" @"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/ble/stack_util/config/factory_config.opt"  -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -Oz -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/app" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/common/cc26xx" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/ti/posix/ticlang" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/include" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/source/third_party/freertos/portable/GCC/ARM_CM0" -I"D:/ti/simplelink_lowpower_f3_sdk_9_14_02_16/kernel/freertos" -DICALL_NO_APP_EVENTS -DCC23X0 -DNVOCMP_NWSAMEITEM=1 -DNVOCMP_NVPAGES=6 -DFREERTOS -DNVOCMP_POSIX_MUTEX -gdwarf-3 -Wunused-function -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"D:/cc2340_project/basic_ble_LP_EM_CC2340R5_freertos_ticlang/Release/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


